### ISSUE TITLE
Question about scenes

### ISSUE THREAD

**Issue by Coiado** [TuyaInc/tuyasmart_home_ios_sdk#10]
Hello,

I would like to turn on a smart lamp everyday at 14:00 Shanghai's time zone, to do that I'm using the follow code in swift:
 ```
let sceneName = "temp"
 let action = TuyaSmartSceneActionModel()
 action?.entityId = device.devId
 action?.actionExecutor = "dpIssue"
 action?.executorProperty = ["1":true]
 let condition = TuyaSmartSceneConditionModel()
 condition?.entityId = device.devId
 condition?.expr = [["timeZoneId": "Asia/Shanghai", "loops": "1111111", "time":"14:00", "date": "20190211"]]
 let homeId = JibSmartHome.sharedInstance.home!.homeModel.homeId
 TuyaSmartScene.addNewScene(withName: sceneName, homeId: homeId,
                            background: "", showFirstPage: false,
                            conditionList: [condition!], actionList: [action!],
                            matchType: TuyaSmartConditionMatchAll,
                            success: { sceneModel in
                               self.scene = TuyaSmartScene(sceneModel: sceneModel)
                               self.scene?.enable(success: {
                                       self.dismiss(animated: true, completion: nil)
                            }, failure: { error in
                                       print(error?.localizedDescription)
                            })
}, failure: {optionalError in
            if let err = optionalError {
                print(error?.localizedDescription)
            }
})
```

My application is executing the success block, but my lamp isn't turn on at 14:00. I already try to modify my scene adding a ruleTrigger action, but it didn't work too. On the other side, when I execute my scene, my lamp turn on no matter what time, it seems that my condition and my action are not linked. Do you know what I did wrong? There are some way to program my lamp to turn on everyday at 14?

Thank you very much.

**Comment by LeonQi0317** [comment]
There are some suggestions:
1. condition?.entityId changed to "timer".
2. matchType changed to TuyaSmartConditionMatchAny.
3. When created an automation, the automation is default enabled, so you don't need to enable it.
Try to change the above three.
