### ISSUE TITLE
Regarding p2pId & Password

### ISSUE THREAD

**Issue by rajesh0092** [TuyaInc/tuyasmart_home_ios_sdk#11]
Not able to get p2pId & password when calling device list with details api.

**Comment by 0x5e** [comment]
Hi, could you please provide more details about log or code? what's the p2pld & password? @rajesh0092

**Comment by rajesh0092** [comment]
"skills" : {
            "p2pType" : 1
          },

I am getting p2pType But not getting p2pId & password.

**Comment by 0x5e** [comment]
I don't know the type of your product, please contact our project manager for help. go to https://iot.tuya.com and click online contact, provide your pid to our team. thanks
