### ISSUE TITLE
单设备分享

### ISSUE THREAD

**Issue by KevinDengSir** [TuyaInc/tuyasmart_home_ios_sdk#12]
你好，情况是这样的：
基于自有用户体系登入涂鸦SDK，也就是UID登入，然后单设备共享的步骤是什么？

**Comment by xuchengcheng** [comment]
现在提供有邀请分享接口 和 确认分享接口 两个接口支持UID。
TuyaSmartHomeDeviceShare 
/**
 邀请分享接口
 
 @param countryCode 国家码
 @param userAccount 账号
 @param devId       设备Id
 @param success     操作成功回调
 @param failure     操作失败回调
 */
- (void)inviteShareWithCountryCode:(NSString *)countryCode
                       userAccount:(NSString *)userAccount
                             devId:(NSString *)devId
                           success:(TYSuccessInt)success
                           failure:(TYFailureError)failure;

/**
 确认分享接口
 
 @param shareId     邀请分享接口返回的shareId
 @param success     操作成功回调
 @param failure     操作失败回调
 */
- (void)confirmInviteShareWithShareId:(NSInteger)shareId
                              success:(TYSuccessHandler)success
                              failure:(TYFailureError)failure;

**Comment by xuchengcheng** [comment]
现在只支持 UID 邀请分享和确认分享的功能，不支持 UID 直接分享。如果有需求，可以联系产品经理进行排期开发。

**Comment by KevinDengSir** [comment]
好的，谢谢。
