### ISSUE TITLE
打开运行崩溃

### ISSUE THREAD

**Issue by OldStoryMrwang** [TuyaInc/tuyasmart_home_ios_sdk#14]
TuyaSmartHomeKit_Example[26331:4756871] *** Terminating app due to uncaught exception 'start sdk error', reason: 'security image not found'

并且 t_s.bmp文件缺失

**Comment by xuchengcheng** [comment]
SDK 版本大于等于 2.8.43，需要在涂鸦开发平台申请新的AppKey，AppSecret，和安全图片。
使用方式可以参考 https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/zh-hans/resource/Preparation.html

**Comment by OldStoryMrwang** [comment]
ok了 谢谢
