### ISSUE TITLE
Document for Door Lock Development

### ISSUE THREAD

**Issue by rajesh0092** [TuyaInc/tuyasmart_home_ios_sdk#15]
Please share the document how to develop Door Lock Device Or sample app for the same.

**Comment by xuchengcheng** [comment]
SDK Doc ： https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/en/
SDK Demo : https://github.com/TuyaInc/tuyasmart_home_ios_sdk
SDK includes: network configuration, control, status reporting, regular tasks, groups, firmware upgrades, sharing. But not for a specific product.
