### ISSUE TITLE
About sensor question

### ISSUE THREAD

**Issue by KevinDengSir** [TuyaInc/tuyasmart_home_ios_sdk#16]
Hello, I'm trying to develop sensors。
But I don't know where to get the historical data from the sensor records.
Is it accessed through your API?？
Thank you for your help.

**Comment by xuchengcheng** [comment]
operation log

| name of the api | version | describe |
| ------------ | ------------- | ------------ |
| m.smart.operate.log | 2.0 | get the operation history log |


### request parm

| name | type | describe | Whether the required parameters |
| ------------ | ------------- | ------------ | ------------ |
| devId | String | device ID | true|
| dpIds | String | The DP points to be queried are separated by , | true|
| offset | Integer | Paging offset | true|
| limit | Integer | Page size, number of data bars per page | true|
| sortType | String | Sort by time, ASC, DESC, default DESC | false|
