### ISSUE TITLE
ZigBee 网关添配问题

### ISSUE THREAD

**Issue by KevinDengSir** [TuyaInc/tuyasmart_home_ios_sdk#17]
你好，是关于添配 ZigBee 网关的问题，我们按照文档上的 ”ZigBee 网关配网“ 进行编码，前段时间是可以添配成功的，然后这星期开始就一直添配不上了。xcode 的控制台一直输出这样的 
logs：
2019-04-24 18:13:21.183223+0800 ****[8647:3702571] TYActivatorService: searchDevice
2019-04-24 18:13:21.195427+0800 ****[8647:3702571] TYGetSTimerService get timer from sTimer
2019-04-24 18:13:21.197365+0800 ****[8647:3702571] method is https://a1.tuyacn.com/api.json?osSystem=12.1.2&timeZoneId=Asia%2FShanghai&clientId=ydcju98mwykhfx7kfq4p&sign=0f1908febdecf151d8849dbc46bee287&a=tuya.m.device.list.token&time=1556100801&deviceId=42B222F9-F9D1-45A6-935B-6AD566873E27&os=IOS&platform=iPhone%207&sid=ay155124N7696997sYHbpRz370c0288497070c026377b876a2e2fb9e&lang=zh-Hans-CN&appVersion=1.2.24&ttid=sdk_appstore@ydcju98mwykhfx7kfq4p&sdkVersion=2.0.0&v=2.0&,postData is {
    token = n7XlMB25;
}
2019-04-24 18:13:21.259475+0800 ****[8647:3703357] ATRequest response is tuya.m.device.list.token {
    result =     {
    };
    status = ok;
    success = 1;
    t = 1556100801241;
}
然后代理 - (void)activator:(TuyaSmartActivator *)activator didReceiveDevice:(TuyaSmartDeviceModel *)deviceModel error:(NSError *)error 一直没有回调回来

非常需要你的帮助，谢谢。

**Comment by xuchengcheng** [comment]
我需要更多的本地日志来判断网关是否被激活

**Comment by xuchengcheng** [comment]
我把这个issues 关掉，你可以去涂鸦开发者平台提个工单，会有人帮你查找问题的。

**Comment by adnan1naeem** [comment]
can you please help me out as i am having this issue??

**Comment by fujijing** [comment]
The log means  device failed to connect to the network, please ensure that the device is ready for network connection and change a Wi-Fi network or set the router signal type to 2.4 GHz

> can you please help me out as i am having this issue??
> 
> ```
> 2020-03-11 16:59:29.157354+0500 ios[508:47541]  --- network config failure {
>     currentTime = 1583927969;
>     step = token;
>     token = EUMDVuRzhWSBFF;
>     type = "wifi_config_ez_3";
> }```.
> I am having issues while using Activator
> ```

The log means  device failed to connect to the network, please ensure that the device is ready for network connection and change a Wi-Fi network or set the router signal type to 2.4 GHz

**Comment by adnan1naeem** [comment]
> The log means device failed to connect to the network, please ensure that the device is ready for network connection and change a Wi-Fi network or set the router signal type to 2.4 GHz
> 
> > can you please help me out as i am having this issue??
> > ```
> > 2020-03-11 16:59:29.157354+0500 ios[508:47541]  --- network config failure {
> >     currentTime = 1583927969;
> >     step = token;
> >     token = EUMDVuRzhWSBFF;
> >     type = "wifi_config_ez_3";
> > }```.
> > I am having issues while using Activator
> > ```
> 
> The log means device failed to connect to the network, please ensure that the device is ready for network connection and change a Wi-Fi network or set the router signal type to 2.4 GHz

i am using following api :
sdk_1.TuyaActivatorApi.initActivator({
                    homeId: params.homeId,
                    password: params.key,
                    ssid: params.ssid,
                    time: 50,
                    type: 'TY_EZ',
                });
It just timeout in response.
