### ISSUE TITLE
Problem with the SDK

### ISSUE THREAD

**Issue by FirmwareDeveloper** [TuyaInc/tuyasmart_home_ios_sdk#18]
Hello all,

We have some Heaters with Tuya WiFi module in them, all of the can connect to Tuya app and function very well. However we have our own app to connect to our Tuya based products. Some of these heaters can connect to our app but some can not connect. 

Any ideas on what is the problem?

Thank you in advance.
Shaham

-------------------------------------------------------------------------------
大家好，

我们有一些带有Tuya WiFi模块的加热器，所有这些都可以连接到Tuya app并且运行良好。 但是，我们有自己的应用程序连接到我们的Tuya产品。 其中一些加热器可以连接到我们的应用程序，但有些无法连接。

关于什么是问题的任何想法？

先感谢您。
Shaham

**Comment by xuchengcheng** [comment]
Can you give me more useful information ?
Is based on the iOS SDK development ?
Which function is have a problem? device activator or device control ?

**Comment by FirmwareDeveloper** [comment]
Hello xuchengcheng,
Well, with both Android and ios I have this problem.
I can get the device connected to the internet (I can see the device connected to the router), I can see the device on my app, but when I want to connect to it refuses the connection.
I can also share the SDK log of my app when trying to connect to device to my app, where one succeed and one fails.

Thank you in advance :-)

[defective_device.txt](https://github.com/TuyaInc/tuyasmart_home_ios_sdk/files/3166527/defective_device.txt)
[good_device.txt](https://github.com/TuyaInc/tuyasmart_home_ios_sdk/files/3166528/good_device.txt)

**Comment by 0x5e** [comment]
Hi @FirmwareDeveloper , you have two devices with different type, their pid and schema are totally different, can't be treated as the same.

**Comment by 0x5e** [comment]
devId = 7038220468c63adaadf5; productId = stmkpqhxqYuP15Xr; Power/TempSet/TempCurrent/Timer/Countdown
devId = 002006646001943a0b16; productId = 0zVMuzyZxXFlyxuu; switch/temperature_c/temperature_f/exchange/c_temperature/f_temperature/appoint/appoint_flag

these two product are different.

**Comment by FirmwareDeveloper** [comment]
Thanks a lot @0x5e , is this difference in the Tuya WiFi module or in the MCU?
Is schema defined in the WiFi module or in the MCU?
Is it possible to fix this problem with over the air update of the firmware or MCU firmware?
