### ISSUE TITLE
How to make a universal app from Tuya SDK?

### ISSUE THREAD

**Issue by FirmwareDeveloper** [TuyaInc/tuyasmart_home_ios_sdk#19]
I have 2 products (both heaters) which are supposed to be exactly the same model and functionality, but apparently the supplier put different MCUs in them.
Surprisingly both of them can be controlled via Tuya app as heater. But only one of them can be controlled via my app. 

My question is how Tuya doesn't care about the difference in MCU and both can be controlled via Tuya app, but my in-house developed app cares about the MCU? What makes Tuya app different from my app? How can I make my app a universal app like Tuya app?

I would be thankful if someone can help with my problem.

Best Regards,

**Comment by xuchengcheng** [comment]
Please provide deviceId on controllable and uncontrollable devices.

**Comment by FirmwareDeveloper** [comment]
Dear @xuchengcheng ,

Thanks for your reply.
controllable: devId = 7038220468c63adaadf5
uncontrollable: devId = 002006646001943a0b16

I should also mention that we have more than 500 products and we do not know how many of them are controllable with our app and how many uncontrollable. These device IDs are from the sample that we randomly picked for test.

**Comment by 0x5e** [comment]
devId = 7038220468c63adaadf5; pid = stmkpqhxqYuP15Xr;
devId = 002006646001943a0b16; pid = 0zVMuzyZxXFlyxuu;

this are two type of product. their pid are different. you said '500 products', did you mean '500 devices' ? you can seprate them with pid.

**Comment by FirmwareDeveloper** [comment]
Yes 500 devices.
You mean I can separate them in the app??
At the moment, the first one can connect to my app but the second one can not. However both of them are connected to Tuya app as heater device. How two different type of products can work as a heater with the Tuya app, but Just one of them can work with my app?
This is actually my main question.

**Comment by xuchengcheng** [comment]
Through different device UI panels to control different productId.

**Comment by FirmwareDeveloper** [comment]
can we have just one control panel with all standard functions for a heater to solve our problem?
or we need multiple control panels with different set of functions for a heater?

**Comment by 0x5e** [comment]
You can have one big control panel with all standard functions for a heater, or  multiple control panels with different functions, it all depends on you. for each device, you should read it's pid and schema, then you can know what function it has and what function not.

**Comment by FirmwareDeveloper** [comment]
Thanks to your answer now I know what to do with the UI.
But as you mentioned in your earlier comment, in my case, I have two different products with different PIDs (that's because the supplier used some other MCUs which belong to another customer).
Since in my new UI I will have all the standard functions for a heater, I am not worried about the schema anymore, because my UI is flexible now. 

But what about the PID? should my app care about PID as well?
