### ISSUE TITLE
1、下载demo后，跑不起来

### ISSUE THREAD

**Issue by BzHuang** [TuyaInc/tuyasmart_home_ios_sdk#20]
下载demo，pod install 成功后跑不起来

**Comment by xuchengcheng** [comment]
报什么错误？是不是没有导入安全证书，APPKey 和 APPSecret 有填进去吗？

**Comment by BzHuang** [comment]
![屏幕快照 2019-05-16 21 13 07](https://user-images.githubusercontent.com/13215355/57856876-7f355900-7820-11e9-8a96-9d85bab5a18f.png)
![屏幕快照 2019-05-16 21 19 33](https://user-images.githubusercontent.com/13215355/57856878-7fcdef80-7820-11e9-9921-b55430e3e76a.png)
具体报什么错不清楚，就是跑不起来，真机虚拟机都不行。

**Comment by BzHuang** [comment]
APPKey 和 APPSecret 都填了，Bundle identifier也改为对应的自己申请的app

**Comment by xuchengcheng** [comment]
podfile 里面SDK是怎么引用的？
建议引用方式：
platform :ios, '8.0'
target 'your_target_name' do
      pod "TuyaSmartHomeKit"
end

还有你现在引用的是哪个版本？
demo是测试过没问题，你pod update 下再试试

**Comment by BzHuang** [comment]
新建的工程引入sdk可以跑起来，是指在这里下载的demo跑不来，想参考demo是怎么开发的。

**Comment by BzHuang** [comment]
可以了，之前不知道怎么不行

**Comment by BzHuang** [comment]
@
