### ISSUE TITLE
Checking Of device category

### ISSUE THREAD

**Issue by rajesh0092** [TuyaInc/tuyasmart_home_ios_sdk#21]
Hi,
I added door lock & camera to my device list.
now I want to check when I will click on camera or door lock. How can I find the category or device type on clicking the device or how can I check which device type I am pressing.
This issue's reason is when I will press the camera it will go to camera view & when I will press the door lock it will go to door lock view.

Please anyone share the solution for the same issue.

**Comment by xuchengcheng** [comment]
You can distinguish different device types by deviceModel.productId.

**Comment by rajesh0092** [comment]
Ok I am getting the deviceModel.productId but how can I check that the product id is for doorlock & for camera.

**Comment by xuchengcheng** [comment]
You can distinguish by deviceModel.category.
doorlock = "ms"
camera = "sp"

**Comment by rajesh0092** [comment]
#############Thanks################

**Comment by rajesh0092** [comment]
Hi,
Can you please share / explain after adding of door lock when I will click on that particular door lock device what functions should I call and Can you please share the sample codes for the same.

**Comment by xuchengcheng** [comment]
You need to understand the device of the data point function.
doc link : https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/en/resource/Device.html#functions-of-device

**Comment by xuchengcheng** [comment]
You can refer to the demo.
demo link: https://github.com/TuyaInc/tuyasmart_home_ios_sdk/tree/master/Example

**Comment by rajesh0092** [comment]
In demo the screen & functionality is totally different from your Tuya app case of door lock so I am getting confuse & not clear about the functionality.
So if you will explain once then may be I can get all points of functionality. Also I attached your app functionality screen which is not in demo.


![Screenshot 2019-05-17 at 1 59 32 PM](https://user-images.githubusercontent.com/48124413/58010699-81dcca80-7b0e-11e9-8a29-4df2bc17172f.png)

**Comment by xuchengcheng** [comment]
The product is created by yourself, So you more clearly the data point function. I can't help you.

**Comment by rajesh0092** [comment]
It's not created by me. I am doing your functionality which is available in your Tuya Smart live app of door lock.

**Comment by xuchengcheng** [comment]
Who created this product information and needed to consult him?

**Comment by rajesh0092** [comment]
1- Excuse me you are creating a random number key with five minute validation.
2- Battery status you are showing on your screen so please tell how will I get two methods????

**Comment by xuchengcheng** [comment]
I don't know the function of this product. SDK is just a channel, and it doesn't care about specific products.

**Comment by rajesh0092** [comment]
Hello,
Can you please check what kind of error it is

publishDps failure: Error Domain=com.tuya.www Code=1507 "dps data type error" UserInfo={NSLocalizedDescription=dps data type error}

**Comment by xuchengcheng** [comment]
Control command format error, you send me requested data and deviceModel.deviceId.

**Comment by xuchengcheng** [comment]
Control command format error, please send me requested data and deviceModel.deviceId.

**Comment by rajesh0092** [comment]
self.device = TuyaSmartDevice(deviceId: deviceId)
        dps = [
            "1": true
        ]
        self.device.publishDps(dps, success: {
            print("publishDps success")
        }, failure: { (error) in
            if let e = error {
                print("publishDps failure: \(e)")
            }
        })

device id --- 12000304807d3a7f7887

**Comment by xuchengcheng** [comment]
Code: 1 type is a value, not a bool.
Please understand the meaning of this device of DPS information first.
Who created the product ?
You need to communicate to look for him.

**Comment by rajesh0092** [comment]
Then Please explain which value should I pass there instead of bool.
Please understand the meaning of this device of DPS information first ---- >
I am not getting that's why asking & posting.Also in your document you have mentioned the same thing.
Who created the product ? --- >
I have no idea.
You need to communicate to look for him. --- >
Please share his contact details or else where should I communicate with him .

**Comment by xuchengcheng** [comment]
Please describe yourself. 
Are you a personal developer? 
Why don't you create the product yourself (https://iot.tuya.com/index)?
Where did you buy the product?
