### ISSUE TITLE
Does cloud send the PID to the app?

### ISSUE THREAD

**Issue by FirmwareDeveloper** [TuyaInc/tuyasmart_home_ios_sdk#22]
Hello,

Would you please let me know how the app can prepares the UI for each product?
Does the cloud receive the PID from the device, the figures out what DPs this PID has and eventually tell the app to prepare the UI?
In another word, does the app needs to receive the PID from cloud or all it needs is the schema (DP IDs)?

Thanks in advance.

**Comment by xuchengcheng** [comment]
You can refer to the demo.
demo link: https://github.com/TuyaInc/tuyasmart_home_ios_sdk/tree/master/Example

**Comment by FirmwareDeveloper** [comment]
Thanks for your reply @xuchengcheng , would you please let me know which part of this demo example I can find my answer?

**Comment by xuchengcheng** [comment]
Demo including user login,  get device list, device control, smart scene , etc
