### ISSUE TITLE
Android提示权限校验失败

### ISSUE THREAD

**Issue by Eafy** [TuyaInc/tuyasmart_home_ios_sdk#25]
提示：涂鸦登录失败[SING_VALIDATE_FALED_4]:权限校验失败4
请问是系统权限还是什么权限？

**Comment by xuchengcheng** [comment]
你可以去Android的仓库去提这个问题

**Comment by xuchengcheng** [comment]
你可以去Android的SDK 去提这个问题。地址： https://github.com/TuyaInc/tuyasmart_home_android_sdk
