### ISSUE TITLE
#define APP_GROUP_NAME your_app_group_name

### ISSUE THREAD

**Issue by Chowing** [TuyaInc/tuyasmart_home_ios_sdk#28]
文件TYUserDefine.h中的一行代码“#define APP_GROUP_NAME your_app_group_name”，那么这个your_app_group_name在哪里可以找到？

**Comment by xuchengcheng** [comment]
主要是用来做：扩展(Extension)需要和主Target数据共享。
如果需要开发APP Extension，请在初始化SDK的时候设置 appGroupId。

现在master 先移除了APP Extension，如果需要可以切换到分支 APPExtension

**Comment by Chowing** [comment]
已经设置了key和SECRET，提示错误 Expanded from macro 'SDK_APPKEY'、Expanded from macro 'SDK_APPSECRET'、Expanded from macro 'APP_GROUP_NAME'

**Comment by xuchengcheng** [comment]
你把key 和 Secret 放在宏定义哪里就可以了。
