### ISSUE TITLE
SDK 现在没有做App extension 的数据共享？

### ISSUE THREAD

**Issue by wenliabc2007** [TuyaInc/tuyasmart_home_ios_sdk#3]
在主app 里面登陆之后，在app extension 中读不到用户的登录数据
建议把UIKeyChainStore 的 service 和 accessGroup 放出来。做成用户可以配置的字段就可以

**Comment by xuchengcheng** [comment]
谢谢你的提问，这个功能已经计划做了，但是没有这么快，等有消息了第一时间通知你。

**Comment by xuchengcheng** [comment]
可以在类 TuyaSmartSDK 设置appGroupId
/**
 *  Application group identifier
 *  If you want to use the SDK in app extension, set `appGroupId` before SDK initialized both in app & app extension.
 *  如果需要开发APP Extension，请在初始化SDK的时候设置 appGroupId
 */
@property (nonatomic, strong) NSString *appGroupId;
