### ISSUE TITLE
Login not works with New SDK

### ISSUE THREAD

**Issue by amacymind** [TuyaInc/tuyasmart_home_ios_sdk#30]
Hello,
I create user from your old ios sdk version. Now its not works with this new sdk version.
If i create new user from latest version then login works fine for that user.

Thanks,

**Comment by xuchengcheng** [comment]
The data upgrading is needed to upgrade TuyaSDK to TuyaHomeSDK. The upgrade Version interface shall be invoked for upgrade.

if ([TuyaSmartSDK sharedInstance].checkVersionUpgrade) {
    [[TuyaSmartSDK sharedInstance] upgradeVersion:^{

    } failure:^(NSError *error) {

    }];
}

**Comment by xuchengcheng** [comment]
link : https://github.com/TuyaInc/tuyasmart_home_ios_sdk
doc : https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/

Tuya Smart APP SDK provides the interface package for the communication with hardware and Tuya Cloud to accelerate the application development process, including the following features:

Hardware functions (network configuration, control, status reporting, regular tasks, groups, firmware upgrades, sharing)
Account system (phone number, email registration, login, password reset and other general account functions)
Tuya Cloud HTTP API interface package

**Comment by amacymind** [comment]
Just tell me where to use this upgradeVersion method in new sdk?

**Comment by amacymind** [comment]
Also i already previously used TuyaHomeSDK then why i required upgrade method?

**Comment by xuchengcheng** [comment]
Sorry, I misunderstood it.

SDK version > 0.2.2, SDK updates the new signature method.
You need to get Appkey, AppSecret, iOS security images, bundleId for application on Tuya Developer Platform.

**Comment by amacymind** [comment]
Yes i do that. But new sdk version 2.12.46 is not worked for my old email password. Every time says 'Incorrect account or password'

**Comment by xuchengcheng** [comment]
Can you provide an account that failed to log in? And  which API did you call?

**Comment by amacymind** [comment]
my email: ankur@macymind.com
API is like,
[[TuyaSmartUser sharedInstance] loginByEmail:@"your_country_code" email:@"your_email" password:@"your_password" success:^{
    NSLog(@"login success");
} failure:^(NSError *error) {
    NSLog(@"login failure: %@", error);
}];

**Comment by xuchengcheng** [comment]
AppKey: hnufanwpnp3u88jgpsq is a new application. 
What is your old AppKey?
Two different AppKey user data are not interoperable.

**Comment by amacymind** [comment]
You mean user is also link with AppKey. Right?

**Comment by xuchengcheng** [comment]
Right

**Comment by amacymind** [comment]
ok thank you

**Comment by amacymind** [comment]
Its works now
