### ISSUE TITLE
TuyaSmartRequest api not works

### ISSUE THREAD

**Issue by amacymind** [TuyaInc/tuyasmart_home_ios_sdk#31]
Hello,
I used TuyaSmartRequest api 'm.smart.dp.his.stat.get.all' & 'm.smart.dp.his.stat.get.month' for get dpId data. But now its not works. Are you changed anything in it?

> TuyaSmartRequest *request = [[TuyaSmartRequest alloc] init];
> [request requestWithApiName:@"m.smart.dp.his.stat.get.all" postData:@{@"devId":deviceModel.devId, @"dpId":@"101"} version:@"1.0" success:^(id result) {
> }
> or
> 
> [request requestWithApiName:@"m.smart.dp.his.stat.get.month" postData:@{@"devId":deviceModel.devId, @"month":@"201909", @"dpId":@"101"} version:@"1.0" success:^(id result){
> }
> 

Its gives error like, Error Domain=com.tuya.www Code=1501 "Parameter or Data Error" UserInfo={NSLocalizedDescription=Parameter or Data Error, NSLocalizedFailureReason=PARAMS_ILLEGAL_OR_DATA_ILLEGAL}

**Comment by xuchengcheng** [comment]
Can you provide the devId?

**Comment by amacymind** [comment]
Here's one for my devId: 33730035807d3a478136

**Comment by xuchengcheng** [comment]
The device history function needs to have statistical authority, and now it has been opened for you. You can try it.

**Comment by amacymind** [comment]
No its not still works.
```
TuyaSmartRequest *request = [[TuyaSmartRequest alloc] init];
[request requestWithApiName:@"m.smart.dp.his.stat.get.all" postData:@{@"devId":@"33730035807d3a478136", @"dpId":@"101"} version:@"1.0" success:^(id result) {
       NSLog(@"result:%@",result);
}failure:^(NSError *error) {
       NSLog(@"error:%@",error);
    }];

```

**Comment by xiaochengxuyuan** [comment]
Parameter dpId:101 for 33730035807d3a478136 is a switch dp and its not supported in this interface.
i guess you can try dpId:103 for the data you want.

**Comment by amacymind** [comment]
Yes I want battery status thats why i used 103. But its gives result like,
```
{
    sum = "0.00";
    thisDay = "0.0";
    years =     {
        2019 =         {
            10 = "0.00";
        };
    };
}
```

What this means?

**Comment by xiaochengxuyuan** [comment]
The result is the electricity you used.

**Comment by amacymind** [comment]
I want device battery status. Just tell me why 'm.smart.dp.his.stat.get.all' & 'm.smart.dp.his.stat.get.month'method not works? Also where is document for that methods previously its shows in tuya doc.

**Comment by tkhabbab** [comment]
sendVerifyCode failure: Error Domain=com.tuya.www Code=1501 "Permission Verification Failed" UserInfo={NSLocalizedDescription=Permission Verification Failed, NSLocalizedFailureReason=SING_VALIDATE_FALED}

How can i solve this issue
