### ISSUE TITLE
你们这个SDK支持摄像头吗

### ISSUE THREAD

**Issue by MasterWen** [TuyaInc/tuyasmart_home_ios_sdk#36]
我们想通过集成你们的SDK兼容你们的摄像头。但是在你们的SDK里没有找到关于摄像头资料

**Comment by xuchengcheng** [comment]
集成IPC地址： https://github.com/TuyaInc/tuyasmart_camera_ios_sdk
文档：https://tuyainc.github.io/tuyasmart_camera_ios_sdk_doc/zh-hans/
