### ISSUE TITLE
SDK升级时的一些问题...

### ISSUE THREAD

**Issue by wwdc14** [TuyaInc/tuyasmart_home_ios_sdk#37]
请问从TuyaSmartKit迁移到`TuyaSmartHomeKit`有没有一个帮助文档？ 比如那些方法已弃用在新的SDK里的替代方法是什么？
目前迁移的不是很顺利。
一些`TuyaSmartKit`的方法到`TuyaSmartHomeKit`不适用，也没有文档可查。
比如获取这个账号下的所有设备`TuyaSmartKit`：`TuyaSmartUser.sharedInstance()?.deviceArray`
`TuyaSmartHomeKit`应该怎么做？
还有TuyaSmartKit下注册的账号到新的`TuyaSmartHomeKit`下能否通用？

**Comment by wwdc14** [comment]
因为老版本没有推送功能，目前根据业务需求只需要集成一个推送功能。
能否在老版本SDK上集成一下推送功能？

**Comment by xuchengcheng** [comment]
TuyaSmartHomeKit 主要是引入了家庭的概念
账户升级的文档：https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/zh-hans/resource/User.html#SDK%E8%B4%A6%E6%88%B7%E5%8D%87%E7%BA%A7

TuyaSmartHomeKit 没有对 TuyaSmartKit 做兼容，所以需要重新适配

老版本已经不维护了
