### ISSUE TITLE
tuyasmart_ios_sdk和tuyasmart_home_ios_sdk 有什么区别?

### ISSUE THREAD

**Issue by KingjZhang** [TuyaInc/tuyasmart_home_ios_sdk#4]
tuyasmart_ios_sdk和tuyasmart_home_ios_sdk 有什么区别?

我用tuyasmart_ios_sdk的,发现有些功能没有.

tuyasmart_home_ios_sdk有更新时区等.

**Comment by xuchengcheng** [comment]
tuyasmart_ios_sdk 是基于2系列的SDK，以后不维护了。不支持家庭管理，zigbee，红外等新功能。会慢慢废弃掉。
tuyasmart_home_ios_sdk 是3系列的SDK，是最新的。支持最新的所有功能，是按照家庭维护管理设备，支持zigbee，红外，wifi网关等最新功能。建议用tuyasmart_home_ios_sdk 3系列 来开发SDK。

**Comment by KingjZhang** [comment]
好,谢谢.
