### ISSUE TITLE
程序运行崩溃

### ISSUE THREAD

**Issue by MasterWen** [TuyaInc/tuyasmart_home_ios_sdk#41]
我导入SDK后调用 [[TuyaSmartSDK sharedInstance] startWithAppKey:SDK_APPKEY secretKey:SDK_APPSECRET]时程序崩溃，报错信息是Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[TYSDKDevice tysdk_UUID]: unrecognized selector sent to class 0x101d074c8'，bundle id appkey appsecret 安全图片都没有问题。

**Comment by xuchengcheng** [comment]
可以发下Podfile.lock的内容，分析下

**Comment by MasterWen** [comment]
PODS:
  - CocoaAsyncSocket (7.6.3)
  - MQTTClient (0.15.2):
    - MQTTClient/Core (= 0.15.2)
  - MQTTClient/Core (0.15.2):
    - MQTTClient/Manager
    - MQTTClient/Min
  - MQTTClient/Manager (0.15.2):
    - MQTTClient/Min
  - MQTTClient/Min (0.15.2)
  - OpenSSL-Universal (1.0.2.17)
  - TuyaCamera (3.13.4)
  - TuyaSmartActivatorKit (3.14.1):
    - TuyaSmartDeviceKit
  - TuyaSmartBaseKit (3.14.2):
    - TuyaSmartUtil
    - YYModel
  - TuyaSmartBLEKit (3.14.0):
    - TuyaSmartActivatorKit
    - TuyaSmartBaseKit
    - TuyaSmartDeviceKit
    - TYBluetooth
  - TuyaSmartBLEMeshKit (3.14.0):
    - OpenSSL-Universal (= 1.0.2.17)
    - TuyaSmartActivatorKit
    - TuyaSmartBaseKit
    - TuyaSmartBLEKit
    - TuyaSmartDeviceKit
    - TYBluetooth
  - TuyaSmartCameraBase (4.2.6)
  - TuyaSmartCameraKit (4.3.2):
    - TuyaSmartBaseKit
    - TuyaSmartCameraBase
    - TuyaSmartCameraM
    - TuyaSmartDeviceKit
  - TuyaSmartCameraM (4.2.6):
    - TuyaCamera
    - TuyaSmartBaseKit
    - TuyaSmartCameraBase
    - TuyaSmartDeviceKit
  - TuyaSmartCameraT (3.2.0):
    - TuyaSmartBaseKit
    - TuyaSmartCameraBase
    - TuyaSmartDeviceKit
  - TuyaSmartDeviceKit (3.14.1):
    - TuyaSmartBaseKit
    - TuyaSmartMQTTChannelKit
    - TuyaSmartSocketChannelKit
  - TuyaSmartFeedbackKit (3.12.2):
    - TuyaSmartBaseKit
  - TuyaSmartHomeKit (3.14.0):
    - TuyaSmartActivatorKit
    - TuyaSmartBaseKit
    - TuyaSmartBLEKit
    - TuyaSmartBLEMeshKit
    - TuyaSmartDeviceKit
    - TuyaSmartFeedbackKit
    - TuyaSmartMessageKit
    - TuyaSmartMQTTChannelKit
    - TuyaSmartSceneKit
    - TuyaSmartSocketChannelKit
    - TuyaSmartTimerKit
  - TuyaSmartMessageKit (3.12.2):
    - TuyaSmartBaseKit
  - TuyaSmartMQTTChannelKit (3.14.0):
    - MQTTClient (= 0.15.2)
    - TuyaSmartBaseKit
  - TuyaSmartSceneKit (3.14.2):
    - TuyaSmartBaseKit
    - TuyaSmartDeviceKit
  - TuyaSmartSocketChannelKit (3.14.0):
    - CocoaAsyncSocket
    - TuyaSmartBaseKit
  - TuyaSmartTimerKit (3.13.0):
    - TuyaSmartBaseKit
    - TuyaSmartDeviceKit
  - TuyaSmartUtil (3.14.8)
  - TYBluetooth (3.14.0)
  - YYModel (1.0.4)

DEPENDENCIES:
  - TuyaSmartCameraKit
  - TuyaSmartCameraT
  - TuyaSmartHomeKit

SPEC REPOS:
  trunk:
    - CocoaAsyncSocket
    - MQTTClient
    - OpenSSL-Universal
    - TuyaCamera
    - TuyaSmartActivatorKit
    - TuyaSmartBaseKit
    - TuyaSmartBLEKit
    - TuyaSmartBLEMeshKit
    - TuyaSmartCameraBase
    - TuyaSmartCameraKit
    - TuyaSmartCameraM
    - TuyaSmartCameraT
    - TuyaSmartDeviceKit
    - TuyaSmartFeedbackKit
    - TuyaSmartHomeKit
    - TuyaSmartMessageKit
    - TuyaSmartMQTTChannelKit
    - TuyaSmartSceneKit
    - TuyaSmartSocketChannelKit
    - TuyaSmartTimerKit
    - TuyaSmartUtil
    - TYBluetooth
    - YYModel

SPEC CHECKSUMS:
  CocoaAsyncSocket: eafaa68a7e0ec99ead0a7b35015e0bf25d2c8987
  MQTTClient: 902c7bcac1501595f3d0b15178c7205b40331fb0
  OpenSSL-Universal: ff04c2e6befc3f1247ae039e60c93f76345b3b5a
  TuyaCamera: 35892b381ed29013359e5ae2b506ac4ab9a6d935
  TuyaSmartActivatorKit: d07ce11bf12254903839dc9ee8fe3b27aeeb1fec
  TuyaSmartBaseKit: f6f7987e862e6b1bb132d966a257f7895b77713d
  TuyaSmartBLEKit: bb899c0b660fb33f6a8f876b07bae002896539a6
  TuyaSmartBLEMeshKit: 26c959e8a66e379e00160cdbb8c63990d7297eab
  TuyaSmartCameraBase: 17272ae43036035bedb8e0f8f8175d5fa52b00fe
  TuyaSmartCameraKit: cc72c97694153c3bcadbec5918fb1da5222895f2
  TuyaSmartCameraM: 86a3cc1d9b3d174bfc6814690559f2d86c599563
  TuyaSmartCameraT: 0d1e45295a0e2858a722935b1ca6a97841984fae
  TuyaSmartDeviceKit: afd76bf477e6a88cbe9eb18270c61fb94fd50264
  TuyaSmartFeedbackKit: f847e9c8f19c9cb561e4e11bb1bc0f515ba5b11a
  TuyaSmartHomeKit: c16cda0dca115d8f8392e42541ff4519bd6b3493
  TuyaSmartMessageKit: e732a8e2f8cc8e3d3d5edf2ad9c269c245371d23
  TuyaSmartMQTTChannelKit: d78d301516294239a3db96bc7b81b1e667d4a40d
  TuyaSmartSceneKit: 235ea1b7bd1cd0f2eee30836376a4c87701e73b7
  TuyaSmartSocketChannelKit: 286654a004f3b6f81b6c2277cab2cfac72a21156
  TuyaSmartTimerKit: 3296a4e8ab503f6f6e84849591cfc3492c28a5ed
  TuyaSmartUtil: a4370126ae4f182f6d3a63d8a35bb71938b2a91b
  TYBluetooth: c6ed6134ecfca0cbe88aef6037b0efa8a01067b4
  YYModel: 2a7fdd96aaa4b86a824e26d0c517de8928c04b30

PODFILE CHECKSUM: 3fd3e7a3e571c3f6580c5720f63a86ee6b166bf3

COCOAPODS: 1.8.4

**Comment by MasterWen** [comment]
PODS:

CocoaAsyncSocket (7.6.3)

MQTTClient (0.15.2):
MQTTClient/Core (= 0.15.2)


MQTTClient/Core (0.15.2):
MQTTClient/Manager

MQTTClient/Min


MQTTClient/Manager (0.15.2):
MQTTClient/Min


MQTTClient/Min (0.15.2)

OpenSSL-Universal (1.0.2.17)

TuyaCamera (3.13.4)

TuyaSmartActivatorKit (3.14.1):
TuyaSmartDeviceKit


TuyaSmartBaseKit (3.14.2):
TuyaSmartUtil

YYModel


TuyaSmartBLEKit (3.14.0):
TuyaSmartActivatorKit

TuyaSmartBaseKit

TuyaSmartDeviceKit

TYBluetooth


TuyaSmartBLEMeshKit (3.14.0):
OpenSSL-Universal (= 1.0.2.17)

TuyaSmartActivatorKit

TuyaSmartBaseKit

TuyaSmartBLEKit

TuyaSmartDeviceKit

TYBluetooth


TuyaSmartCameraBase (4.2.6)

TuyaSmartCameraKit (4.3.2):
TuyaSmartBaseKit

TuyaSmartCameraBase

TuyaSmartCameraM

TuyaSmartDeviceKit


TuyaSmartCameraM (4.2.6):
TuyaCamera

TuyaSmartBaseKit

TuyaSmartCameraBase

TuyaSmartDeviceKit


TuyaSmartCameraT (3.2.0):
TuyaSmartBaseKit

TuyaSmartCameraBase

TuyaSmartDeviceKit


TuyaSmartDeviceKit (3.14.1):
TuyaSmartBaseKit

TuyaSmartMQTTChannelKit

TuyaSmartSocketChannelKit


TuyaSmartFeedbackKit (3.12.2):
TuyaSmartBaseKit


TuyaSmartHomeKit (3.14.0):
TuyaSmartActivatorKit

TuyaSmartBaseKit

TuyaSmartBLEKit

TuyaSmartBLEMeshKit

TuyaSmartDeviceKit

TuyaSmartFeedbackKit

TuyaSmartMessageKit

TuyaSmartMQTTChannelKit

TuyaSmartSceneKit

TuyaSmartSocketChannelKit

TuyaSmartTimerKit


TuyaSmartMessageKit (3.12.2):
TuyaSmartBaseKit


TuyaSmartMQTTChannelKit (3.14.0):
MQTTClient (= 0.15.2)

TuyaSmartBaseKit


TuyaSmartSceneKit (3.14.2):
TuyaSmartBaseKit

TuyaSmartDeviceKit


TuyaSmartSocketChannelKit (3.14.0):
CocoaAsyncSocket

TuyaSmartBaseKit


TuyaSmartTimerKit (3.13.0):
TuyaSmartBaseKit

TuyaSmartDeviceKit


TuyaSmartUtil (3.14.8)

TYBluetooth (3.14.0)

YYModel (1.0.4)

DEPENDENCIES:

TuyaSmartCameraKit

TuyaSmartCameraT

TuyaSmartHomeKit

SPEC REPOS:
trunk:
- CocoaAsyncSocket
- MQTTClient
- OpenSSL-Universal
- TuyaCamera
- TuyaSmartActivatorKit
- TuyaSmartBaseKit
- TuyaSmartBLEKit
- TuyaSmartBLEMeshKit
- TuyaSmartCameraBase
- TuyaSmartCameraKit
- TuyaSmartCameraM
- TuyaSmartCameraT
- TuyaSmartDeviceKit
- TuyaSmartFeedbackKit
- TuyaSmartHomeKit
- TuyaSmartMessageKit
- TuyaSmartMQTTChannelKit
- TuyaSmartSceneKit
- TuyaSmartSocketChannelKit
- TuyaSmartTimerKit
- TuyaSmartUtil
- TYBluetooth
- YYModel

SPEC CHECKSUMS:
CocoaAsyncSocket: eafaa68a7e0ec99ead0a7b35015e0bf25d2c8987
MQTTClient: 902c7bcac1501595f3d0b15178c7205b40331fb0
OpenSSL-Universal: ff04c2e6befc3f1247ae039e60c93f76345b3b5a
TuyaCamera: 35892b381ed29013359e5ae2b506ac4ab9a6d935
TuyaSmartActivatorKit: d07ce11bf12254903839dc9ee8fe3b27aeeb1fec
TuyaSmartBaseKit: f6f7987e862e6b1bb132d966a257f7895b77713d
TuyaSmartBLEKit: bb899c0b660fb33f6a8f876b07bae002896539a6
TuyaSmartBLEMeshKit: 26c959e8a66e379e00160cdbb8c63990d7297eab
TuyaSmartCameraBase: 17272ae43036035bedb8e0f8f8175d5fa52b00fe
TuyaSmartCameraKit: cc72c97694153c3bcadbec5918fb1da5222895f2
TuyaSmartCameraM: 86a3cc1d9b3d174bfc6814690559f2d86c599563
TuyaSmartCameraT: 0d1e45295a0e2858a722935b1ca6a97841984fae
TuyaSmartDeviceKit: afd76bf477e6a88cbe9eb18270c61fb94fd50264
TuyaSmartFeedbackKit: f847e9c8f19c9cb561e4e11bb1bc0f515ba5b11a
TuyaSmartHomeKit: c16cda0dca115d8f8392e42541ff4519bd6b3493
TuyaSmartMessageKit: e732a8e2f8cc8e3d3d5edf2ad9c269c245371d23
TuyaSmartMQTTChannelKit: d78d301516294239a3db96bc7b81b1e667d4a40d
TuyaSmartSceneKit: 235ea1b7bd1cd0f2eee30836376a4c87701e73b7
TuyaSmartSocketChannelKit: 286654a004f3b6f81b6c2277cab2cfac72a21156
TuyaSmartTimerKit: 3296a4e8ab503f6f6e84849591cfc3492c28a5ed
TuyaSmartUtil: a4370126ae4f182f6d3a63d8a35bb71938b2a91b
TYBluetooth: c6ed6134ecfca0cbe88aef6037b0efa8a01067b4
YYModel: 2a7fdd96aaa4b86a824e26d0c517de8928c04b30

PODFILE CHECKSUM: 3fd3e7a3e571c3f6580c5720f63a86ee6b166bf3

COCOAPODS: 1.8.4





Best Regards


&nbsp;Sui




&nbsp;Shenzhen Lanbon Hi-Tech CO., LTD. -- Smart Home Specialist.


&nbsp;http://www.lanbona.com
&nbsp;Add：3rd Floor,ZhanRun Business Building,Yunfeng Road No.1,QueShan Industrial Area,Dalang,Longhua district,Shenzhen,China


&nbsp;E-mail:&nbsp;lanbon@lanbon.cn&nbsp; &nbsp; &nbsp; &nbsp;Phone: 86-13760134983
&nbsp;Tel:86-755-29407818&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Fax：86-755-29407882




&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by xuchengcheng** [comment]
你在Build Settings中的link--->Other Linker Flags  中收到删除了：-all_load或者-force-load 这样会造成category 加载不了，你可以去修改下。

**Comment by MasterWen** [comment]
这个问题我也试出来了，但是在Other Linker Flags 添加了$(inherited)，我使用的一个摄像头的SDK就会报错。

Undefined symbols for architecture arm64:
 
&nbsp; "_mi_h265decoder_create", referenced from:
 
&nbsp; &nbsp; &nbsp; -[NVMediaPlayer decodeImageData:] in libNVSDK.a(NVMediaPlayer.o)
 
&nbsp; &nbsp; &nbsp; -[NVMediaPlayer decodeFileImageData:] in libNVSDK.a(NVMediaPlayer.o)
 
&nbsp; "_mi_h265decoder_decodeframe", referenced from:
 
&nbsp; &nbsp; &nbsp; -[NVMediaPlayer decodeImageData:] in libNVSDK.a(NVMediaPlayer.o)
 
&nbsp; &nbsp; &nbsp; -[NVMediaPlayer decodeFileImageData:] in libNVSDK.a(NVMediaPlayer.o)







Best Regards


&nbsp;Sui




&nbsp;Shenzhen Lanbon Hi-Tech CO., LTD. -- Smart Home Specialist.


&nbsp;http://www.lanbona.com
&nbsp;Add：3rd Floor,ZhanRun Business Building,Yunfeng Road No.1,QueShan Industrial Area,Dalang,Longhua district,Shenzhen,China


&nbsp;E-mail:&nbsp;lanbon@lanbon.cn&nbsp; &nbsp; &nbsp; &nbsp;Phone: 86-13760134983
&nbsp;Tel:86-755-29407818&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Fax：86-755-29407882




&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by xuchengcheng** [comment]
你可以去cameraKit仓库提问下
