### ISSUE TITLE
ios other linker flag添加objc

### ISSUE THREAD

**Issue by MasterWen** [TuyaInc/tuyasmart_home_ios_sdk#42]
使用你们SDK，在other linker flag添加objc以后导致项目里一些第三方报错，不添加objc你们的SDK无法使用，怎么解决,如何把-objc换成-force_load.

**Comment by xuchengcheng** [comment]
你是不是修改了other linker flag里面的东西。你如果是pod 集成，在other linker flag 

![image](https://user-images.githubusercontent.com/4865346/71716543-169ef900-2e50-11ea-9eb2-9389424bf285.png)

**Comment by MasterWen** [comment]
是这样的，你们SDK 需要在other linker flags里添加$(inheried),但是$(inheried)里面包含-ObjC，这样就导致了我们原有的一些第三方报错。但是如果我把-ObjC去掉你们的SDK就无法使用了。我是想问有没有可以替代-ObjC，我尝试了使用-force_load但是依然有问题




Best Regards


&nbsp;Sui




&nbsp;Shenzhen Lanbon Hi-Tech CO., LTD. -- Smart Home Specialist.


&nbsp;http://www.lanbona.com
&nbsp;Add：3rd Floor,ZhanRun Business Building,Yunfeng Road No.1,QueShan Industrial Area,Dalang,Longhua district,Shenzhen,China


&nbsp;E-mail:&nbsp;lanbon@lanbon.cn&nbsp; &nbsp; &nbsp; &nbsp;Phone: 86-13760134983
&nbsp;Tel:86-755-29407818&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Fax：86-755-29407882




&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by xuchengcheng** [comment]
你原来的三方库也是pod 集成的吗？$(inheried) 这个是pod 集成添加的，不是SDK的问题。

**Comment by MasterWen** [comment]
不是直接导入到项目里的，你们的SDK只能通过pod下载吗？有没有下载的SDK直接倒入到项目。


Best Regards


&nbsp;Sui




&nbsp;Shenzhen Lanbon Hi-Tech CO., LTD. -- Smart Home Specialist.


&nbsp;http://www.lanbona.com
&nbsp;Add：3rd Floor,ZhanRun Business Building,Yunfeng Road No.1,QueShan Industrial Area,Dalang,Longhua district,Shenzhen,China


&nbsp;E-mail:&nbsp;lanbon@lanbon.cn&nbsp; &nbsp; &nbsp; &nbsp;Phone: 86-13760134983
&nbsp;Tel:86-755-29407818&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Fax：86-755-29407882




&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by xuchengcheng** [comment]
不建议手动集成，因为很多配置项，cocoapods 已经帮我们配置好了，手动集成问题会很多。
