### ISSUE TITLE
你们SDK和其他SDK发生冲突

### ISSUE THREAD

**Issue by MasterWen** [TuyaInc/tuyasmart_home_ios_sdk#43]
关于OTHER_LDFLAGS = $(inherited) -ObjC -l"BlocksKit" -l"CocoaAsyncSocket" -l"MBProgressHUD" -l"MQTTClient" -l"Masonry" -l"Reachability" -l"SDWebImage" -l"YYModel" -l"c++" -l"crypto" -l"ssl" -l"z" -framework "CFNetwork" -framework "CoreBluetooth" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreTelephony" -framework "Foundation" -framework "ImageIO" -framework "MessageUI" -framework "Security" -framework "SystemConfiguration" -framework "TYBluetooth" -framework "TuyaSmartActivatorKit" -framework "TuyaSmartBLEKit" -framework "TuyaSmartBLEMeshKit" -framework "TuyaSmartBaseKit" -framework "TuyaSmartDeviceKit" -framework "TuyaSmartFeedbackKit" -framework "TuyaSmartMQTTChannelKit" -framework "TuyaSmartMessageKit" -framework "TuyaSmartSceneKit" -framework "TuyaSmartSocketChannelKit" -framework "TuyaSmartTimerKit" -framework "TuyaSmartUtil" -framework "UIKit"

1.你们的SDK里面需要在other linker flag里添加 $(inherited），不添加就会程序运行会报错。如何解决
2.如果必须添加$(inherited）可以不添加-ObjC么？-ObjC和我们的其他SDK发生冲突

**Comment by xuchengcheng** [comment]
不建议SDK 手动集成，你可以把现在的三方库都改成pod 自动集成可以不？

**Comment by xuchengcheng** [comment]
如果必须添加$(inherited）可以不添加-ObjC么？-ObjC和我们的其他SDK发生冲突。

这个具体和那些SDK 冲突？

**Comment by MasterWen** [comment]
有冲突的SDK是一款摄像头的不是你们的。主要是因为，他的SDK无法在other linker flag里添加-ObjC。这个SDK由于供应商的问题，无法通过pod导入

**Comment by xuchengcheng** [comment]
你可以联系他们，让他们去支持吗？

**Comment by MasterWen** [comment]
这个暂时没办法，我们联系不到原公司，我们也是拿的别人的。现在就是你们的SDK -ObjC是没办法去掉的是吧。因为尝试去掉，但是执行代码就会崩溃。出现这个Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[TYSDKDevice tysdk_UUID]: unrecognized selector sent to class 0x100a7d648'

**Comment by 0x5e** [comment]
需要加上-Objc和-all_load，否则sdk中的category都无法加载。

**Comment by xuchengcheng** [comment]
你如果一定要手动继承的话，可以参考podspec里面参数的设置。
你这边在我们IoT 平台提一个工单，我们会提供技术支持。

**Comment by MasterWen** [comment]
具体在哪里提交工单，需要填写什么

**Comment by xuchengcheng** [comment]
联系下产品经理，基于SDK开发的，需要APPKey，APPSecret和安全图片，这个就是在涂鸦 IoT 平台申请的。
你提个工单，我们提供私下技术支持。

**Comment by MasterWen** [comment]
我提交工单你们会发一份SDK给我吗？不通过pod的方式。

**Comment by xuchengcheng** [comment]
SDK 是可以 pod 到本地的，然后你手动继承，我的意思是给你提供技术支持。

**Comment by MasterWen** [comment]
我之前有尝试过但是还是出现Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[TYSDKDevice tysdk_UUID]: unrecognized selector sent to class 0x100a7d648'这个错误

**Comment by MasterWen** [comment]
你们的SDK包含的文件是在太多了，如果我现在只是想先集成配置部分，需要倒入哪些文件

**Comment by xuchengcheng** [comment]
你提工单，我们给你提供私下的技术支持。
