### ISSUE TITLE
Issue with bitcode when use cocoa pods.

### ISSUE THREAD

**Issue by Lyankar** [TuyaInc/tuyasmart_home_ios_sdk#46]
ld: '/Users/******/Desktop/TuyaMeshExample/Pods/TuyaCameraSDK/ios/TuyaCameraSDK.framework/TuyaCameraSDK' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/*****/Desktop/TuyaMeshExample/Pods/TuyaCameraSDK/ios/TuyaCameraSDK.framework/TuyaCameraSDK' for architecture arm64

**Comment by 0x5e** [comment]
This is TuyaCameraSDK, not TuyaSmartHomeKit. Currently TuyaCameraSDK doesn't support bitcode, please disable this feature.
