### ISSUE TITLE
This device is not supported by this app

### ISSUE THREAD

**Issue by UltimoAlves** [TuyaInc/tuyasmart_home_ios_sdk#47]
Hello.
I'm trying to integrate SDK with my test App and i am with the follow error:

Error Domain=com.tuya.www Code=1501 "This device is not supported by this app" UserInfo={NSLocalizedDescription=This device is not supported by this app, NSLocalizedFailureReason=APP_PRODUCT_UNSUPPORT}

How can i fix it?

**Comment by huangdaxiaEX** [comment]
Please confirm whether your product id is bound by other applications. 

If yes, contact the owner of the product to add your application or unbind restrictions.
