### ISSUE TITLE
Device IOT

### ISSUE THREAD

**Issue by UltimoAlves** [TuyaInc/tuyasmart_home_ios_sdk#48]
I'm trying to add an IOT device to my SDK application, but I always get this message: "Error Domain=com.tuya.www Code=1501 "This device is not supported by this app" UserInfo={NSLocalizedDescription=This device is not supported by this app, NSLocalizedFailureReason=APP_PRODUCT_UNSUPPORT}""

I would like to know if I can connect any TUYA devices (from any company) to my SDK application or do I need company authorization?

**Comment by huangdaxiaEX** [comment]
Yes, `APP_PRODUCT_UNSUPPORT` means it needs to be authorized by other companies.
