### ISSUE TITLE
After robot turned on, takes 10-30 seconds to update app status

### ISSUE THREAD

**Issue by KingjZhang** [TuyaInc/tuyasmart_home_ios_sdk#5]
Hi @xuchengcheng 

After robot turned on, takes 10-30 seconds to update app status. After the robot turned off, takes ~1-3 minute to update the app status. Can we reduce the time? How to do it?

就是如果robot冷开机,需要10秒以上才能在app端通过tuya sdk接受到状态变更成在线,如果离线,可能需要1-2分钟以上才能在app端更新状态,有什么办法可以提高吗?如果打开app时,robot是开机的,需要3-5秒左右.也可以通过调用什么接口改善吗?

**Comment by xuchengcheng** [comment]
1、设备冷启动，需要10S是因为设备启动也需要时间，然后去连接wifi，wifi连接成功后，再去连接云端。
2、设备离线，需要1-2分钟，是因为离线后设备和云端都在尝试互相重连，尝试重连的时间1-2分钟不定。
3、打开APP时，设备的在线状态是从云端拉取的，正常情况1S内会回来的，当设备列表设备非常多或者网络比较差的时候云端返回会比较慢。主要取决于手机网络的状况。
