### ISSUE TITLE
单设备接入

### ISSUE THREAD

**Issue by Ramonfan** [TuyaInc/tuyasmart_home_ios_sdk#51]
你好我们现在想了解基于tuya sdk开放单品app，就是如果没有家庭的概念，请问设备的一个绑定流程是怎样的，我看现在的sdk接口绑定流程，要先获取绑定token，但是都需要传home ID呀

**Comment by 0x5e** [comment]
可以在进入首页的时候拉取家庭列表，如果家庭数为0，自动创建一个家庭，不在UI展示即可。目前设备都是绑定到家庭下面的。
