### ISSUE TITLE
uid 登录直接崩溃

### ISSUE THREAD

**Issue by YFBig-Heart** [TuyaInc/tuyasmart_home_ios_sdk#58]
-[TuyaSmartMQTTConfigModel setUseQUIC:]: unrecognized selector sent to instance 0x282c39920

**Comment by 0x5e** [comment]
@YFBig-Heart 麻烦提供一下Podfile.lock文件

**Comment by YFBig-Heart** [comment]
解决了，MQTT库版本过低导致的
