### ISSUE TITLE
Error installing TuyaSmartTimerKit

### ISSUE THREAD

**Issue by tkhabbab** [TuyaInc/tuyasmart_home_ios_sdk#60]
[!] Error installing TuyaSmartTimerKit
[!] /usr/bin/curl -f -L -o /var/folders/fg/6q2lrqjj4hq51mfnhtv4y4br0000gn/T/d20200901-1178-1b3af4f/file.zip https://airtake-public-data.oss-cn-hangzhou.aliyuncs.com/smart/app/package/sdk/ios/TuyaSmartTimerKit-3.13.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 15  421k   15 65330    0     0   1137      0  0:06:19  0:00:57  0:05:22 10408
curl: (18) transfer closed with 365829 bytes remaining to read

**Comment by 0x5e** [comment]
Hi @tkhabbab , It's a network issue, and it's not a dns issue, please have a retry.
