### ISSUE TITLE
Installation of tuyaSmartHomeKit ios sdk gives error

### ISSUE THREAD

**Issue by nimesh1997** [TuyaInc/tuyasmart_home_ios_sdk#65]
Hello,
I tried to install tuya ios sdk using pods but I get an error. 
[!] Error installing TuyaSmartHomeKit
I also attached screenshot below.

<img width="1232" alt="Screenshot 2020-10-31 at 11 42 40 AM" src="https://user-images.githubusercontent.com/26666178/97773154-66834500-1b73-11eb-94b2-fda7922032c4.png">

Please tell me is this a server issue or my region issue?
Thanks

**Comment by TuyaRonbin** [comment]
Please provide the contents of the file podfile

**Comment by nimesh1997** [comment]
@xuchengcheng I had attached the contents of the pod file below.

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  #for Tuya SDK
  pod "TuyaSmartHomeKit", "3.17.0"
  #for Tuya Smart camera
  #pod "TuyaSmartCamera"
  pod "TuyaSmartCameraKit"


  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.1' # <--- add this
    end
  end
end

**Comment by TuyaRonbin** [comment]
SDK now has version dependency, it is recommended to change to the following:

#for Tuya SDK
pod "TuyaSmartHomeKit"
#for Tuya Smart camera
pod "TuyaSmartCameraKit"

**Comment by nimesh1997** [comment]
Thanks it works.

**Comment by aqibzigron** [comment]
i am not able to installed sdk since last two days 

[!] Error installing TYDeviceSyncModule
[!] /usr/bin/curl -f -L -o /var/folders/s3/pmgntkf54mn19lj1mp1_8h6c0000gn/T/d20230916-640-2libbu/file.zip https://airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com/smart/app/package/pods/ios/TYDeviceSyncModule-4.0.0-feature-420bizbundle.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 73 7266k   73 5322k    0     0  11189      0  0:11:05  0:08:07  0:02:58     0
curl: (56) Recv failure: Connection reset by peer
