### ISSUE TITLE
Tuya SDK TuyaSmartMQTTConfigModel setUseQUIC problem 

### ISSUE THREAD

**Issue by tkhabbab** [TuyaInc/tuyasmart_home_ios_sdk#67]
###  It error when is call 
 TuyaSmartSDK.sharedInstance().start(withAppKey:"", secretKey:"") my appkey and secretKey is correct. 

`2020-11-02 13:20:12.772549+0600 KhabbbabIOT[5069:1809216] -[TuyaSmartMQTTConfigModel setUseQUIC:]: unrecognized selector sent to instance 0x28365fb40
2020-11-02 13:20:12.774117+0600 Khabbab  IOT[5069:1809216] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TuyaSmartMQTTConfigModel setUseQUIC:]: unrecognized selector sent to instance 0x28365fb40'
*** First throw call stack:
(0x1bd220654 0x1bcf42bcc 0x1bd124dd8 0x1bd2247f8 0x1bd22671c 0x10365f708 0x1bd17c504 0x1bd17c54c 0x1bd17b8a4 0x1bd17b57c 0x1bd0f82d4 0x1bd17aedc 0x1bd4e8974 0x1035f15e4 0x102f7c11c 0x102f7c6d0 0x1c0c8c65c 0x1c0c910ec 0x1c0c914f4 0x1c0bf0d68 0x1c0c04c30 0x1c0c05fd0 0x1c0be9530 0x1c17887fc 0x1c3d25494 0x1c3d2b5ec 0x1c3d36128 0x1c3c7eb44 0x1c3ca84e4 0x1c3ca8ef8 0x1bd19df2c 0x1bd198e20 0x1bd19929c 0x1bd198ba8 0x1c7308344 0x1c12d43e4 0x102efa9bc 0x1bd0208f0)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TuyaSmartMQTTConfigModel setUseQUIC:]: unrecognized selector sent to instance 0x28365fb40'
terminating with uncaught exception of type NSException`

**Comment by 0x5e** [comment]
@tkhabbab Can you please check the Podfile.lock file, make sure all tuya sdk have the same minor version, for example:
TuyaSmartBaseKit ~> 3.20.0
TuyaSmartDeviceKit ~> 3.20.0
TuyaSmartMQTTChannelKit ~> 3.20.0

**Comment by tkhabbab** [comment]
<img width="548" alt="Screenshot 2020-11-02 at 3 22 03 PM" src="https://user-images.githubusercontent.com/13781274/97851130-2b257980-1d1f-11eb-89ef-1fa966875ace.png">
_Installing TuyaSmartActivatorKit 3.20.2 (was 3.17.6)
Installing TuyaSmartBLEKit 3.20.1 (was 3.17.8)
Installing TuyaSmartBLEMeshKit 3.20.3 (was 3.17.7)
Installing TuyaSmartBaseKit 3.20.1 (was 3.19.2)
Installing TuyaSmartDeviceCoreKit (3.20.3)
Installing TuyaSmartDeviceKit 3.20.1 (was 3.17.11)
Installing TuyaSmartFeedbackKit 3.20.0 (was 3.15.0)
Installing TuyaSmartHomeKit 3.20.0 (was 3.17.6)
Installing TuyaSmartMQTTChannelKit 3.20.0 (was 3.13.4)
Installing TuyaSmartQUIC (1.1.1)
Installing TuyaSmartSceneKit 3.20.0 (was 3.17.10)
Installing TuyaSmartSocketChannelKit 3.20.1 (was 3.19.0)
Installing TuyaSmartTimerKit 3.20.2 (was 3.18.3)
Installing TuyaSmartUtil 3.20.2 (was 3.19.0)
Installing nanopb 2.30906.0 (was 1.30906.0)
_

I'm Using    pod 'TuyaSmartHomeKit','~> 3.20.0'

**Comment by tkhabbab** [comment]
It's work now after update pod
