### ISSUE TITLE
Doorbell of p2pType "4" is unable to show the live video.

### ISSUE THREAD

**Issue by nimesh1997** [TuyaInc/tuyasmart_home_ios_sdk#68]
Hi,
While opening doorbell of p2pType 4 I got an below mentioned errror, previous month it is working fine but now it is not working and not showing the live video.
`
23496385 [31mERROR[0m [90msrc/tuya_rtc.c:1566:[0m rtc session 1 connect timeout
23496385 [32mINFO [0m [90msrc/tuya_rtc.c:1763:[0m rtc session 1 state change: P2P_CONNECT -> FAILED
23496385 [32mINFO [0m [90msrc/tuya_rtc.c:5457:[0m close session 1
23496392 [32mINFO [0m [90msrc/tuya_rtc.c:3358:[0m destroy rtc session 1
didOccurredError called with : TYCameraErrorCode(rawValue: 1)
23496509 [32mINFO [0m [90msrc/tuya_rtc.c:4424:[0m can not find rtc session
23496509 [32mINFO [0m [90msrc/tuya_rtc.c:4424:[0m can not find rtc session
23496509 [32mINFO [0m [90msrc/tuya_rtc.c:4424:[0m can not find rtc session
23496509 [32mINFO [0m [90msrc/tuya_rtc.c:4424:[0m can not find rtc session
23496509 [32mINFO [0m [90msrc/tuya_rtc.c:4424:[0m can not find rtc session
`
Please help to resolve find the problem.
Thanks!

**Comment by tuyaLang** [comment]
Please provide the device id and a more complete console log

**Comment by nimesh1997** [comment]
I had fixed this issue after doing some changes in my code. Thanks.
