### ISSUE TITLE
Product Id in a group

### ISSUE THREAD

**Issue by Coiado** [TuyaInc/tuyasmart_home_ios_sdk#7]
Hello,
I'm trying to create a group of devices with the function `TuyaSmartGroup.createGroup`, but there's a parameter called `productId`, where can I find this ID? In the documentation, they said we must use the user device list, but I can't find the `groupId` in my device list.

**Comment by Coiado** [comment]
Thank you very much for your answer! Now I can create a group, but I saw that some `productIds` in my `deviceList` are not the same, what make they different? Is there a unique `productId` for each `deviceList`?

**Comment by 0x5e** [comment]
`productId` represents the type of product, `devId` represents the unique id of the specific device. 
For example, `Smart plug A` and `Smart plug B` have the same `productId`, but different `devId`.

**Comment by Coiado** [comment]
I see, but if I try to create my own group with a plug and a lamp, which `productId` should I use? Because everytime I create a group with different devices I have the Error: "No permission", I can only create group with the same devices?

**Comment by 0x5e** [comment]
Yes, different product can't in same group.
