### ISSUE TITLE
M1芯片的Mac，在模拟器上编译报错

### ISSUE THREAD

**Issue by banxin** [TuyaInc/tuyasmart_home_ios_sdk#75]
在模拟器上编译报错

![image](https://user-images.githubusercontent.com/26829487/112711023-55f7b080-8f00-11eb-9e94-7111cda7f540.png)

使用Mac和真机编译，没有问题

![image](https://user-images.githubusercontent.com/26829487/112710990-116c1500-8f00-11eb-8c08-b79c335d8e23.png)

**Comment by 0x5e** [comment]
@banxin  你好，这个是已知问题，请先选择Mac进行开发和调试，我们之后会出xcframework版本解决。
