### ISSUE TITLE
When uploading to ios the build is rejected because of UIWebView

### ISSUE THREAD

**Issue by rahulmr-rently** [TuyaInc/tuyasmart_home_ios_sdk#77]
When uploading to iOS test flight the build is rejected because of UIWebView. 
  s.ios.frameworks = 'CoreTelephony', 'Foundation', 'SystemConfiguration', 'UIKit'
https://github.com/TuyaInc/tuyasmart_home_ios_sdk/blob/1940ce6f872878ac26b7995503617a8a00521bd5/TuyaSmartUtil.podspec#L14

Error from apple:
Dear Developer,

We identified one or more issues with a recent delivery for your app, "XXXX (1018). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Can this be please changed to wkwebview . We are not able to push our app because of this issue .We are really blocked.

**Comment by 0x5e** [comment]
Tuya SDK didn't contain UIWebView. the dSYM file has all UIKit things include UITableView, UIButon, UIWebview, and so on. Usually, the dSYM file won't make your app rejected. The workaround is to remove the Tuya SDK dSYM file after pod install. we will fix this issue in the next release.
