### ISSUE TITLE
Question about smart IR

### ISSUE THREAD

**Issue by Coiado** [TuyaInc/tuyasmart_home_ios_sdk#9]
Hello,
I'm trying to use a smart IR device to learn a code from infrared control and send the same code using my app, I'm setting the `dps["1"] ` as "study" and I take the code from the `dps["2"] ` (study_code), but how can I send this code by smart IR ? I'm trying to set `dps["1"] ` as "send_ir" and publish this code in `dps["3"]` (ir_code) but it's not working, is there something I forgot?
Thank you for your help.

**Comment by 0x5e** [comment]
Hi,
This is a specific product, please login https://iot.tuya.com and click "online consult" button, provide the  smart IR productId and this question to our team, our hardware engineer will answer this question. Thanks

**Comment by Coiado** [comment]
Thank you, this solve my problem!
Just one last question, I saw in Tuya app that when you connect with a Smart IR you have access of database with all IR code of different devices and different brands. Can I have access of this database using your API? 
Thank you one more time for your help.

**Comment by 0x5e** [comment]
Currently we don't provide the api of IR code, sorry about that.

**Comment by Coiado** [comment]
Okay, thank you for your answer

**Comment by OOZAER** [comment]
Hello,

Could you share your solution for send_ir to the community ?

I have similar problem to send ir to universal ir remote from my diy home domotic system.

Thank you

**Comment by marcherdiego** [comment]
Does anyone have the DPS/commands list for this kind of IR devices? it's kinda annoying not being able to find any documentation about it.
